### ISSUE TITLE
Supersnappy can raise an unlisted exception

### ISSUE THREAD

**Issue by Clonkk** [guzba/supersnappy#4]
Using supersnappy with Nim ~~1.6.0~~ devel : 
```
/home/rcaillaud/.nimble/pkgs/supersnappy-2.1.1/supersnappy.nim(323, 56) template/generic instantiation from here
/home/rcaillaud/.nimble/pkgs/supersnappy-2.1.1/supersnappy.nim(341, 35) Error: newSeq(16384) can raise an unlisted exception: Exception
```

**Comment by guzba** [comment]
I am not seeing this with Nim 1.6.0 myself. What is your `nim` command and do you possibly have any flags / features enabled possibly changing behavior? For example, does a simple `nimble test` run?

**Comment by Clonkk** [comment]
It only happens if you compile with --gc:orc.

**Comment by guzba** [comment]
Hm, interesting. Thanks for the info. It seems odd to me --gc:orc makes newSeq raise a generic "Exception". I wonder why that is. Will need to take a look.

**Comment by guzba** [comment]
I added a bunch more test runs to Github Actions and am still not seeing any issues with --gc:orc and Nim 1.6 (or any other version). See this commit: https://github.com/guzba/supersnappy/commit/8deba1f26c6259cf4d97ae04e6f1edd0ec3ac1bc and these runs: https://github.com/guzba/supersnappy/runs/4305537686?check_suite_focus=true

Are you certain you're on stable 1.6? What OS are you seeing this on?

**Comment by Clonkk** [comment]
Supersnappy is at commit 62a7e2cea977e51b60005c64741e15ef91cdf542 (I pulled your latest, but I had the same behaviour with tag v2.1.1).

OS is Ubuntu; Nim compiler is devel (v1.6.0 seems to work, I forgot I was using devel )
```$nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-11-15
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 6976d18519d102c9cc857a84a4b10b009c1e1a38
```

**Comment by disruptek** [comment]
Their CI doesn't use 1.6.1 _and they don't test 1.7.1_.

**Comment by guzba** [comment]
Closing this. It's old and was a devel issue. Reopen if still relevant.
